// packages/vue/src/EventGlobe.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue'
import { EventGlobeRenderer } from '@event-globe/ts'
import type { EventGlobeRendererConfig, ArcOptions, GlobeEvents, GlobeEventLifecycle, GlobeEventOptionsMap } from '@event-globe/ts'

interface Props {
  config?: EventGlobeRendererConfig
}

const { config } = defineProps<Props>()
  
const emit = defineEmits<{
  arcRemoved: [id: number, options: ArcOptions];
}>()

const containerRef = ref<HTMLDivElement>()
let renderer: EventGlobeRenderer | null = null

onMounted(() => {
  if (containerRef.value) {
    renderer = new EventGlobeRenderer(containerRef.value, config)
    renderer.onArcRemoved((id, options) => {
      emit('arcRemoved', id, options)
    })
  }
})

onUnmounted(() => {
  if (renderer) {
    renderer.destroy()
    renderer = null
  }
})

function addArc(options: ArcOptions): number | undefined {
  return renderer?.addArc(options)
}

function addEvent<TGlobeEvent extends GlobeEvents>(
  event: TGlobeEvent,
  options: GlobeEventOptionsMap[TGlobeEvent],
): GlobeEventLifecycle<TGlobeEvent> | undefined {
  return renderer?.addEvent(event, options)
}

function getActiveArcCount(): number {
  return renderer?.getActiveArcCount() ?? 0
}

watch(
  () => config,
  (newConfig) => {
    if (newConfig)
        renderer?.updateConfig(newConfig)
  }
)

defineExpose({
  addEvent,
  addArc,
  getActiveArcCount,
  removeArcById: (id: number) => renderer?.removeArcById(id),
  removeAllEvents: () => renderer?.removeAllEvents(),
  clearAllArcs: () => renderer?.clearAllArcs(),
})
</script>

<template>
  <div ref="containerRef" style="width: 100%; height: 100%"></div>
</template>

// packages/svelte/src/EventGlobe.svelte
<svelte:options customElement="event-globe" runes={true} />

<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import { EventGlobeRenderer } from '@event-globe/ts'
  import type { EventGlobeRendererConfig, ArcOptions, GlobeEvents, GlobeEventLifecycle, GlobeEventOptionsMap } from '@event-globe/ts'

  interface Props {
    config: EventGlobeRendererConfig | undefined
  }

  let { config }: Props = $props()
  
  let containerRef: HTMLDivElement
  let renderer: EventGlobeRenderer | null = null
  
  onMount(() => {
    if (containerRef) {
      renderer = new EventGlobeRenderer(containerRef, config)
      renderer.onArcRemoved((id: number, options: ArcOptions) => {
        
        $host().dispatchEvent(new CustomEvent('arcremoved', { detail: { id, options } }))
      })
    }
  })

  onDestroy(() => {
    if (renderer) {
      renderer.destroy()
      renderer = null
    }
  })

  $effect(() => {
    if (renderer && config) {
      renderer.updateConfig(config)
    }
  })

  export function addEvent<TGlobeEvent extends GlobeEvents>(
    event: TGlobeEvent,
    options: GlobeEventOptionsMap[TGlobeEvent],
  ): GlobeEventLifecycle<TGlobeEvent> | undefined {
    return renderer?.addEvent(event, options)
  }

  export function addArc(options: ArcOptions): number {
    return renderer?.addArc(options) ?? -1
  }

  export function getActiveArcCount(): number {
    return renderer?.getActiveArcCount() ?? 0
  }

  export function removeArcById(id: number): void {
    renderer?.removeArcById(id)
  }

  export function clearAllArcs(): void {
    renderer?.clearAllArcs()
  }

  export function removeAllEvents(): void {
    renderer?.removeAllEvents()
  }
</script>

<div bind:this={containerRef} style="width: 100%; height: 100%"></div>
