// playgrounds/svelte/src/App.svelte
<script lang="ts">
  /* eslint-disable no-console */
  import { onMount } from 'svelte'
  import EventGlobe from '@event-globe/svelte'

  let globeRef: any

  onMount(() => {
    // set interval to add events every 2 seconds
    const interval = setInterval(() => {
      const lat = (Math.random() * 180) - 90
      const lng = (Math.random() * 360) - 180
      const endLat = (Math.random() * 180) - 90
      const endLng = (Math.random() * 360) - 180
      const color = `#${Math.floor(Math.random() * 16777215).toString(16).padStart(6, '0')}`

      const event = globeRef?.addEvent({
        event: 'arc',
        lat,
        lng,
        endLat,
        endLng,
        color,
        showRipple: true,
        showEndRipple: true,
      })

      void event?.finished.then((result: unknown) => {
        console.log('Event finished:', result)
      })

      console.log('Added random event:', { lat, lng, endLat, endLng, color })
    }, 2000)

    console.log('EventGlobe Renderer initialized')

    return () => clearInterval(interval)
  })
</script>

<EventGlobe bind:this={globeRef} config={{ autoRotate: false }} />

// playgrounds/vue/src/App.vue
<script setup lang="ts">
/* eslint-disable no-console */
import { ref, onMounted, onUnmounted } from 'vue'
import EventGlobe from '@event-globe/vue'

const globeRef = ref<any>(null)
let interval: number | null = null

onMounted(() => {
  // set interval to add events every 2 seconds
  interval = setInterval(() => {
    const lat = (Math.random() * 180) - 90
    const lng = (Math.random() * 360) - 180
    const endLat = (Math.random() * 180) - 90
    const endLng = (Math.random() * 360) - 180
    const color = `#${Math.floor(Math.random() * 16777215).toString(16).padStart(6, '0')}`

    const event = globeRef.value?.addEvent({
      event: 'arc',
      lat,
      lng,
      endLat,
      endLng,
      color,
      showRipple: true,
      showEndRipple: true,
    })

    void event?.finished.then((result: unknown) => {
      console.log('Event finished:', result)
    })

    console.log('Added random event:', { lat, lng, endLat, endLng, color })
  }, 2000)

  console.log('EventGlobe Renderer initialized')
})

onUnmounted(() => {
  if (interval) {
    clearInterval(interval)
  }
})
</script>

<template>
  <EventGlobe ref="globeRef" :config="{ autoRotate: false }" style="width: 100%; height: 100vh" />
</template>

<style scoped>
</style>
