// packages/solid/src/EventGlobe.tsx
import { onMount, onCleanup, createEffect } from 'solid-js'
import { EventGlobeRenderer } from '@event-globe/ts'
import type { EventGlobeRendererConfig, ArcOptions, GlobeEvents, GlobeEventLifecycle, GlobeEventOptionsMap } from '@event-globe/ts'

interface EventGlobeProps {
  config?: EventGlobeRendererConfig
  style?: string | Record<string, string>
  class?: string
  ref?: (ref: EventGlobeRef) => void
  onArcRemoved?: (id: number, options: ArcOptions) => void
}

export interface EventGlobeRef {
  addEvent: <TGlobeEvent extends GlobeEvents>(event: TGlobeEvent, options: GlobeEventOptionsMap[TGlobeEvent]) => GlobeEventLifecycle<TGlobeEvent> | undefined
  addArc: (options: ArcOptions) => number
  getActiveArcCount: () => number
  removeArcById: (id: number) => void
  removeAllEvents: () => void
  clearAllArcs: () => void
}

export function EventGlobe(props: EventGlobeProps) {
  let containerRef!: HTMLDivElement
  let renderer: EventGlobeRenderer | null = null

  onMount(() => {
    if (containerRef) {
      renderer = new EventGlobeRenderer(containerRef, props.config)

      if (props.onArcRemoved) {
        renderer.onArcRemoved(props.onArcRemoved)
      }

      // Expose methods via ref if provided
      if (props.ref) {
        props.ref({
          addEvent: (event, options) => renderer?.addEvent(event, options),
          addArc: (options: ArcOptions) => renderer?.addArc(options) ?? -1,
          getActiveArcCount: () => renderer?.getActiveArcCount() ?? 0,
          removeArcById: (id: number) => renderer?.removeArcById(id),
          removeAllEvents: () => renderer?.removeAllEvents(),
          clearAllArcs: () => renderer?.clearAllArcs(),
        })
      }
    }
  })

  onCleanup(() => {
    if (renderer) {
      renderer.destroy()
      renderer = null
    }
  })

  createEffect(() => {
    if (renderer && props.config) {
      renderer.updateConfig(props.config)
    }
  })

  createEffect(() => {
    if (renderer && props.onArcRemoved) {
      renderer.onArcRemoved(props.onArcRemoved)
    }
  })

  return (
    <div
      ref={containerRef}
      style={{ width: '100%', height: '100%', ...(typeof props.style === 'object' ? props.style : {}) }}
      class={props.class}
    />
  )
}

// packages/react/src/EventGlobe.tsx
import { useRef, useEffect, useImperativeHandle, forwardRef } from 'react'
import { EventGlobeRenderer } from '@event-globe/ts'
import type { EventGlobeRendererConfig, ArcOptions, GlobeEvents, GlobeEventLifecycle, GlobeEventOptionsMap } from '@event-globe/ts'
import type { CSSProperties } from 'react'

interface EventGlobeProps {
  config?: EventGlobeRendererConfig
  style?: CSSProperties
  className?: string
  onArcRemoved?: (id: number, options: ArcOptions) => void
}

export interface EventGlobeRef {
  addEvent: <TGlobeEvent extends GlobeEvents>(event: TGlobeEvent, options: GlobeEventOptionsMap[TGlobeEvent]) => GlobeEventLifecycle<TGlobeEvent> | undefined
  addArc: (options: ArcOptions) => number
  getActiveArcCount: () => number
  removeArcById: (id: number) => void
  removeAllEvents: () => void
  clearAllArcs: () => void
}

export const EventGlobe = forwardRef<EventGlobeRef, EventGlobeProps>(
  ({ config, style, className, onArcRemoved }, ref) => {
    const containerRef = useRef<HTMLDivElement>(null)
    const rendererRef = useRef<EventGlobeRenderer | null>(null)

    useEffect(() => {
      if (!containerRef.current)
        return
      if (rendererRef.current)
        return

      rendererRef.current = new EventGlobeRenderer(containerRef.current, config)

      if (onArcRemoved) {
        rendererRef.current.onArcRemoved(onArcRemoved)
      }

      return () => {
        rendererRef.current?.destroy()
        rendererRef.current = null
      }
    }, [])

    useEffect(() => {
      if (rendererRef.current && onArcRemoved) {
        rendererRef.current.onArcRemoved(onArcRemoved)
      }
    }, [onArcRemoved])

    useEffect(() => {
      if (rendererRef.current && config) {
        rendererRef.current.updateConfig(config)
      }
    }, [config])

    useImperativeHandle(ref, () => ({
      addEvent: (event, options) => {
        return rendererRef.current?.addEvent(event, options)
      },
      addArc: (options: ArcOptions) => {
        return rendererRef.current?.addArc(options) ?? -1
      },
      getActiveArcCount: () => {
        return rendererRef.current?.getActiveArcCount() ?? 0
      },
      removeArcById: (id: number) => {
        rendererRef.current?.removeArcById(id)
      },
      removeAllEvents: () => {
        rendererRef.current?.removeAllEvents()
      },
      clearAllArcs: () => {
        rendererRef.current?.clearAllArcs()
      },
    }))

    return (
      <div
        ref={containerRef}
        style={{ width: '100%', height: '100%', ...style }}
        className={className}
      />
    )
  },
)

EventGlobe.displayName = 'EventGlobe'
